// Load JSON data from files (this would typically be done via an API or file loading in a real scenario)
const corruptionIndexData = 
    {
    "Denmark": 88,
    "New Zealand": 88,
    "Finland": 88,
    "Singapore": 85,
    "Sweden": 85,
    "Switzerland": 84,
    "Norway": 85,
    "Netherlands": 82,
    "Germany": 80,
    "Luxembourg": 81,
    "Australia": 73,
    "Canada": 74,
    "Hong Kong": 76,
    "United Kingdom": 78,
    "Austria": 74,
    "Belgium": 73,
    "Estonia": 74,
    "Iceland": 74,
    "Japan": 73,
    "Ireland": 74,
    "United Arab Emirates": 69,
    "Uruguay": 73,
    "France": 71,
    "Bhutan": 68,
    "Chile": 67,
    "United States": 67,
    "Seychelles": 70,
    "Taiwan": 68,
    "Barbados": 65,
    "Bahamas": 64,
    "Qatar": 63,
    "South Korea": 62,
    "Portugal": 62,
    "Lithuania": 61,
    "Spain": 61,
    "Botswana": 55,
    "Brunei": 60,
    "Israel": 59,
    "Slovenia": 57,
    "Saint Vincent and the Grenadines": 59,
    "Cape Verde": 58,
    "Costa Rica": 58,
    "Cyprus": 53,
    "Latvia": 59,
    "Georgia": 55,
    "Poland": 56,
    "Saint Lucia": 56,
    "Dominica": 55,
    "Czech Republic": 54,
    "Oman": 52,
    "Rwanda": 53,
    "Grenada": 53,
    "Italy": 56,
    "Malta": 54,
    "Mauritius": 54,
    "Saudi Arabia": 53,
    "Malaysia": 48,
    "Namibia": 49,
    "Greece": 49,
    "Armenia": 49,
    "Jordan": 49,
    "Slovakia": 52,
    "Belarus": 41,
    "Croatia": 47,
    "Cuba": 46,
    "São Tomé and Príncipe": 45,
    "Montenegro": 46,
    "Senegal": 43,
    "Bulgaria": 42,
    "Hungary": 43,
    "Jamaica": 44,
    "Romania": 45,
    "South Africa": 44,
    "Tunisia": 44,
    "Ghana": 43,
    "Maldives": 40,
    "Vanuatu": 45,
    "Argentina": 38,
    "Bahrain": 42,
    "China": 45,
    "Kuwait": 43,
    "Solomon Islands": 43,
    "Benin": 42,
    "Guyana": 39,
    "Lesotho": 38,
    "Burkina Faso": 42,
    "India": 40,
    "Morocco": 39,
    "Timor-Leste": 41,
    "Trinidad and Tobago": 41,
    "Turkey": 38,
    "Colombia": 39,
    "Ecuador": 36,
    "Brazil": 38,
    "Ethiopia": 39,
    "Kazakhstan": 37,
    "Peru": 36,
    "Serbia": 38,
    "Sri Lanka": 37,
    "Suriname": 39,
    "Tanzania": 39,
    "Gambia": 37,
    "Indonesia": 38,
    "Albania": 35,
    "Algeria": 33,
    "Ivory Coast": 36,
    "El Salvador": 34,
    "Kosovo": 39,
    "Thailand": 35,
    "Vietnam": 39,
    "Bosnia and Herzegovina": 35,
    "Mongolia": 35,
    "North Macedonia": 39,
    "Panama": 36,
    "Moldova": 36,
    "Philippines": 33,
    "Egypt": 33,
    "Eswatini": 32,
    "Nepal": 33,
    "Sierra Leone": 34,
    "Ukraine": 32,
    "Zambia": 33,
    "Niger": 31,
    "Bolivia": 30,
    "Kenya": 30,
    "Kyrgyzstan": 27,
    "Mexico": 31,
    "Pakistan": 28,
    "Azerbaijan": 30,
    "Gabon": 31,
    "Malawi": 35,
    "Mali": 29,
    "Russia": 29,
    "Laos": 30,
    "Mauritania": 28,
    "Togo": 30,
    "Dominican Republic": 30,
    "Liberia": 29,
    "Myanmar": 28,
    "Paraguay": 30,
    "Angola": 29,
    "Djibouti": 30,
    "Papua New Guinea": 31,
    "Uzbekistan": 28,
    "Uganda": 27,
    "Cameroon": 27,
    "Bangladesh": 26,
    "Madagascar": 26,
    "Mozambique": 26,
    "Guinea": 25,
    "Guatemala": 25,
    "Iran": 25,
    "Tajikistan": 25,
    "Central African Republic": 24,
    "Lebanon": 24,
    "Nigeria": 24,
    "Honduras": 23,
    "Iraq": 23,
    "Cambodia": 23,
    "Zimbabwe": 23,
    "Eritrea": 22,
    "Republic of the Congo": 21,
    "Guinea-Bissau": 21,
    "Comoros": 20,
    "Haiti": 20,
    "Nicaragua": 20,
    "Sudan": 20,
    "Chad": 20,
    "Burundi": 19,
    "Democratic Republic of the Congo": 21,
    "Turkmenistan": 19,
    "Equatorial Guinea": 17,
    "Libya": 17,
    "Afghanistan": 16,
    "North Korea": 16,
    "Yemen": 16,
    "Venezuela": 14,
    "Somalia": 13,
    "Syria": 13,
    "South Sudan": 11
    };

const countryContinentData = {
    
    "Afghanistan": "South Asia",
    "Angola": "Sub-Saharan Africa",
    "Albania": "Europe & Central Asia",
    "Andorra": "Europe & Central Asia",
    "United Arab Emirates": "Middle East & North Africa",
    "Argentina": "Latin America & Caribbean",
    "Armenia": "Europe & Central Asia",
    "American Samoa": "East Asia & Pacific",
    "Antigua and Barbuda": "Latin America & Caribbean",
    "Australia": "East Asia & Pacific",
    "Austria": "Europe & Central Asia",
    "Azerbaijan": "Europe & Central Asia",
    "Burundi": "Sub-Saharan Africa",
    "Belgium": "Europe & Central Asia",
    "Benin": "Sub-Saharan Africa",
    "Burkina Faso": "Sub-Saharan Africa",
    "Bangladesh": "South Asia",
    "Bulgaria": "Europe & Central Asia",
    "Bahrain": "Middle East & North Africa",
    "Bosnia and Herzegovina": "Europe & Central Asia",
    "Belarus": "Europe & Central Asia",
    "Belize": "Latin America & Caribbean",
    "Bermuda": "North America",
    "Bolivia": "Latin America & Caribbean",
    "Brazil": "Latin America & Caribbean",
    "Barbados": "Latin America & Caribbean",
    "Bhutan": "South Asia",
    "Botswana": "Sub-Saharan Africa",
    "Central African Republic": "Sub-Saharan Africa",
    "Canada": "North America",
    "Switzerland": "Europe & Central Asia",
    "Chile": "Latin America & Caribbean",
    "China": "East Asia & Pacific",
    "Cote d'Ivoire": "Sub-Saharan Africa",
    "Cameroon": "Sub-Saharan Africa",
    "Colombia": "Latin America & Caribbean",
    "Comoros": "Sub-Saharan Africa",
    "Costa Rica": "Latin America & Caribbean",
    "Cuba": "Latin America & Caribbean",
    "Cyprus": "Europe & Central Asia",
    "Germany": "Europe & Central Asia",
    "Djibouti": "Middle East & North Africa",
    "Dominica": "Latin America & Caribbean",
    "Denmark": "Europe & Central Asia",
    "Dominican Republic": "Latin America & Caribbean",
    "Algeria": "Middle East & North Africa",
    "Ecuador": "Latin America & Caribbean",
    "Eritrea": "Sub-Saharan Africa",
    "Spain": "Europe & Central Asia",
    "Estonia": "Europe & Central Asia",
    "Ethiopia": "Sub-Saharan Africa",
    "Finland": "Europe & Central Asia",
    "Fiji": "East Asia & Pacific",
    "France": "Europe & Central Asia",
    "Gabon": "Sub-Saharan Africa",
    "United Kingdom": "Europe & Central Asia",
    "Georgia": "Europe & Central Asia",
    "Ghana": "Sub-Saharan Africa",
    "Guinea": "Sub-Saharan Africa",
    "Guinea-Bissau": "Sub-Saharan Africa",
    "Equatorial Guinea": "Sub-Saharan Africa",
    "Greece": "Europe & Central Asia",
    "Grenada": "Latin America & Caribbean",
    "Greenland": "Europe & Central Asia",
    "Guatemala": "Latin America & Caribbean",
    "Guam": "East Asia & Pacific",
    "Guyana": "Latin America & Caribbean",
    "Honduras": "Latin America & Caribbean",
    "Croatia": "Europe & Central Asia",
    "Haiti": "Latin America & Caribbean",
    "Hungary": "Europe & Central Asia",
    "Indonesia": "East Asia & Pacific",
    "India": "South Asia",
    "Ireland": "Europe & Central Asia",
    "Iraq": "Middle East & North Africa",
    "Iceland": "Europe & Central Asia",
    "Israel": "Middle East & North Africa",
    "Italy": "Europe & Central Asia",
    "Jamaica": "Latin America & Caribbean",
    "Jordan": "Middle East & North Africa",
    "Japan": "East Asia & Pacific",
    "Kazakhstan": "Europe & Central Asia",
    "Kenya": "Sub-Saharan Africa",
    "Cambodia": "East Asia & Pacific",
    "Kiribati": "East Asia & Pacific",
    "Kuwait": "Middle East & North Africa",
    "Lebanon": "Middle East & North Africa",
    "Liberia": "Sub-Saharan Africa",
    "Libya": "Middle East & North Africa",
    "Sri Lanka": "South Asia",
    "Lesotho": "Sub-Saharan Africa",
    "Lithuania": "Europe & Central Asia",
    "Luxembourg": "Europe & Central Asia",
    "Latvia": "Europe & Central Asia",
    "Morocco": "Middle East & North Africa",
    "Monaco": "Europe & Central Asia",
    "Moldova": "Europe & Central Asia",
    "Madagascar": "Sub-Saharan Africa",
    "Maldives": "South Asia",
    "Mexico": "Latin America & Caribbean",
    "Marshall Islands": "East Asia & Pacific",
    "North Macedonia": "Europe & Central Asia",
    "Mali": "Sub-Saharan Africa",
    "Malta": "Middle East & North Africa",
    "Myanmar": "East Asia & Pacific",
    "Montenegro": "Europe & Central Asia",
    "Mongolia": "East Asia & Pacific",
    "Northern Mariana Islands": "East Asia & Pacific",
    "Mozambique": "Sub-Saharan Africa",
    "Mauritania": "Sub-Saharan Africa",
    "Mauritius": "Sub-Saharan Africa",
    "Malawi": "Sub-Saharan Africa",
    "Malaysia": "East Asia & Pacific",
    "Namibia": "Sub-Saharan Africa",
    "Niger": "Sub-Saharan Africa",
    "Nigeria": "Sub-Saharan Africa",
    "Nicaragua": "Latin America & Caribbean",
    "Netherlands": "Europe & Central Asia",
    "Norway": "Europe & Central Asia",
    "Nepal": "South Asia",
    "Nauru": "East Asia & Pacific",
    "New Zealand": "East Asia & Pacific",
    "Oman": "Middle East & North Africa",
    "Pakistan": "South Asia",
    "Panama": "Latin America & Caribbean",
    "Peru": "Latin America & Caribbean",
    "Philippines": "East Asia & Pacific",
    "Palau": "East Asia & Pacific",
    "Papua New Guinea": "East Asia & Pacific",
    "Poland": "Europe & Central Asia",
    "Puerto Rico": "Latin America & Caribbean",
    "Portugal": "Europe & Central Asia",
    "Paraguay": "Latin America & Caribbean",
    "Qatar": "Middle East & North Africa",
    "Romania": "Europe & Central Asia",
    "Rwanda": "Sub-Saharan Africa",
    "Saudi Arabia": "Middle East & North Africa",
    "Sudan": "Sub-Saharan Africa",
    "Senegal": "Sub-Saharan Africa",
    "Singapore": "East Asia & Pacific",
    "Solomon Islands": "East Asia & Pacific",
    "Sierra Leone": "Sub-Saharan Africa",
    "El Salvador": "Latin America & Caribbean",
    "San Marino": "Europe & Central Asia",
    "Somalia": "Sub-Saharan Africa",
    "Serbia": "Europe & Central Asia",
    "South Sudan": "Sub-Saharan Africa",
    "Sao Tome and Principe": "Sub-Saharan Africa",
    "Suriname": "Latin America & Caribbean",
    "Slovenia": "Europe & Central Asia",
    "Sweden": "Europe & Central Asia",
    "Eswatini": "Sub-Saharan Africa",
    "Seychelles": "Sub-Saharan Africa",
    "Chad": "Sub-Saharan Africa",
    "Togo": "Sub-Saharan Africa",
    "Thailand": "East Asia & Pacific",
    "Tajikistan": "Europe & Central Asia",
    "Turkmenistan": "Europe & Central Asia",
    "Tonga": "East Asia & Pacific",
    "Trinidad and Tobago": "Latin America & Caribbean",
    "Tunisia": "Middle East & North Africa",
    "Tuvalu": "East Asia & Pacific",
    "Tanzania": "Sub-Saharan Africa",
    "Uganda": "Sub-Saharan Africa",
    "Ukraine": "Europe & Central Asia",
    "Uruguay": "Latin America & Caribbean",
    "United States": "North America",
    "Uzbekistan": "Europe & Central Asia",
    "Vietnam": "East Asia & Pacific",
    "Vanuatu": "East Asia & Pacific",
    "Samoa": "East Asia & Pacific",
    "South Africa": "Sub-Saharan Africa",
    "Zambia": "Sub-Saharan Africa",
    "Zimbabwe": "Sub-Saharan Africa"
    
};
const countryCodeData = {
    
    "Afghanistan": "AFG",
    "Angola": "AGO",
    "Albania": "ALB",
    "Andorra": "AND",
    "United Arab Emirates": "ARE",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "American Samoa": "ASM",
    "Antigua and Barbuda": "ATG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Burundi": "BDI",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Burkina Faso": "BFA",
    "Bangladesh": "BGD",
    "Bulgaria": "BGR",
    "Bahrain": "BHR",
    "Bosnia and Herzegovina": "BIH",
    "Belarus": "BLR",
    "Belize": "BLZ",
    "Bermuda": "BMU",
    "Bolivia": "BOL",
    "Brazil": "BRA",
    "Barbados": "BRB",
    "Bhutan": "BTN",
    "Botswana": "BWA",
    "Central African Republic": "CAF",
    "Canada": "CAN",
    "Switzerland": "CHE",
    "Chile": "CHL",
    "China": "CHN",
    "Cote d'Ivoire": "CIV",
    "Cameroon": "CMR",
    "Colombia": "COL",
    "Comoros": "COM",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Germany": "DEU",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Denmark": "DNK",
    "Dominican Republic": "DOM",
    "Algeria": "DZA",
    "Ecuador": "ECU",
    "Eritrea": "ERI",
    "Spain": "ESP",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Finland": "FIN",
    "Fiji": "FJI",
    "France": "FRA",
    "Gabon": "GAB",
    "United Kingdom": "GBR",
    "Georgia": "GEO",
    "Ghana": "GHA",
    "Guinea": "GIN",
    "Guinea-Bissau": "GNB",
    "Equatorial Guinea": "GNQ",
    "Greece": "GRD",
    "Grenada": "GRL",
    "Greenland": "GTM",
    "Guatemala": "GUM",
    "Guam": "GUY",
    "Guyana": "HND",
    "Honduras": "HRV",
    "Croatia": "HTI",
    "Haiti": "HUN",
    "Hungary": "IDN",
    "Indonesia": "IND",
    "India": "IRL",
    "Ireland": "IRQ",
    "Iraq": "ISL",
    "Iceland": "ISR",
    "Israel": "ITA",
    "Italy": "JAM",
    "Jamaica": "JOR",
    "Jordan": "JPN",
    "Japan": "KAZ",
    "Kazakhstan": "KEN",
    "Kenya": "KHM",
    "Cambodia": "KIR",
    "Kiribati": "KWT",
    "Kuwait": "LBN",
    "Lebanon": "LBR",
    "Liberia": "LBY",
    "Libya": "LKA",
    "Sri Lanka": "LSO",
    "Lesotho": "LTU",
    "Lithuania": "LUX",
    "Luxembourg": "LVA",
    "Latvia": "MAR",
    "Morocco": "MCO",
    "Monaco": "MDA",
    "Moldova": "MDG",
    "Madagascar": "MDV",
    "Maldives": "MEX",
    "Mexico": "MHL",
    "Marshall Islands": "MKD",
    "North Macedonia": "MLI",
    "Mali": "MLT",
    "Malta": "MMR",
    "Myanmar": "MNE",
    "Montenegro": "MNG",
    "Mongolia": "MNP",
    "Northern Mariana Islands": "MOZ",
    "Mozambique": "MRT",
    "Mauritania": "MUS",
    "Mauritius": "MWI",
    "Malawi": "MYS",
    "Malaysia": "NAM",
    "Namibia": "NER",
    "Niger": "NGA",
    "Nigeria": "NIC",
    "Nicaragua": "NLD",
    "Netherlands": "NOR",
    "Norway": "NPL",
    "Nepal": "NRU",
    "Nauru": "NZL",
    "New Zealand": "OMN",
    "Oman": "PAK",
    "Pakistan": "PAN",
    "Panama": "PER",
    "Peru": "PHL",
    "Philippines": "PLW",
    "Palau": "PNG",
    "Papua New Guinea": "POL",
    "Poland": "PRI",
    "Puerto Rico": "PRT",
    "Portugal": "PRY",
    "Paraguay": "QAT",
    "Qatar": "ROU",
    "Romania": "RWA",
    "Rwanda": "SAU",
    "Saudi Arabia": "SDN",
    "Sudan": "SEN",
    "Senegal": "SGP",
    "Singapore": "SLB",
    "Solomon Islands": "SLE",
    "Sierra Leone": "SLV",
    "El Salvador": "SMR",
    "San Marino": "SOM",
    "Somalia": "SRB",
    "Serbia": "SSD",
    "South Sudan": "STP",
    "Sao Tome and Principe": "SUR",
    "Suriname": "SVN",
    "Slovenia": "SWE",
    "Sweden": "SWZ",
    "Eswatini": "SYC",
    "Seychelles": "TCD",
    "Chad": "TGO",
    "Togo": "THA",
    "Thailand": "TJK",
    "Tajikistan": "TKM",
    "Turkmenistan": "TON",
    "Tonga": "TTO",
    "Trinidad and Tobago": "TUN",
    "Tunisia": "TUV",
    "Tuvalu": "TZA",
    "Tanzania": "UGA",
    "Uganda": "UKR",
    "Ukraine": "URY",
    "Uruguay": "USA",
    "United States": "UZB",
    "Uzbekistan": "VNM",
    "Vietnam": "VUT",
    "Vanuatu": "WSM",
    "Samoa": "ZAF",
    "South Africa": "ZMB",
    "Zambia": "ZWE"
    
};

const CountryAvgLifeExpectancy = {
    "Afghanistan": 64.833,
    "Angola": 61.147,
    "Albania": 78.573,
    "Andorra": null,
    "United Arab Emirates": 77.972,
    "Argentina": 76.667,
    "Armenia": 75.087,
    "American Samoa": null,
    "Antigua and Barbuda": 77.016,
    "Australia": 82.9,
    "Austria": 81.89512195,
    "Azerbaijan": 73.005,
    "Burundi": 61.584,
    "Belgium": 81.99512195,
    "Benin": 61.771,
    "Burkina Faso": 61.577,
    "Bangladesh": 72.591,
    "Bulgaria": 75.11219512,
    "Bahrain": 77.292,
    "Bosnia and Herzegovina": 77.401,
    "Belarus": 74.22682927,
    "Belize": 74.623,
    "Bermuda": 81.86658537,
    "Bolivia": 71.513,
    "Brazil": 75.881,
    "Barbados": 79.19,
    "Bhutan": 71.777,
    "Botswana": 69.592,
    "Central African Republic": 53.283,
    "Canada": 82.04878049,
    "Switzerland": 83.90487805,
    "Chile": 80.181,
    "China": 76.912,
    "Cote d'Ivoire": 57.783,
    "Cameroon": 59.292,
    "Colombia": 77.287,
    "Comoros": 64.321,
    "Costa Rica": 80.279,
    "Cuba": 78.802,
    "Cyprus": 80.982,
    "Germany": 81.29268293,
    "Djibouti": 67.112,
    "Dominica": null,
    "Denmark": 81.45121951,
    "Dominican Republic": 74.081,
    "Algeria": 76.88,
    "Ecuador": 77.01,
    "Eritrea": 66.321,
    "Spain": 83.83170732,
    "Estonia": 78.64634146,
    "Ethiopia": 66.597,
    "Finland": 81.98292683,
    "Fiji": 67.444,
    "France": 82.82682927,
    "Gabon": 66.467,
    "United Kingdom": 81.20487805,
    "Georgia": 73.767,
    "Ghana": 64.074,
    "Guinea": 61.602,
    "Guinea-Bissau": 58.322,
    "Equatorial Guinea": 58.735,
    "Greece": 81.63902439,
    "Grenada": 72.397,
    "Greenland": 72.04756098,
    "Guatemala": 74.302,
    "Guam": 80.074,
    "Guyana": 69.906,
    "Honduras": 75.27,
    "Croatia": 78.42439024,
    "Haiti": 64.001,
    "Hungary": 76.3195122,
    "Indonesia": 71.716,
    "India": 69.656,
    "Ireland": 82.70243902,
    "Iraq": 70.604,
    "Iceland": 83.16341463,
    "Israel": 82.80487805,
    "Italy": 83.49756098,
    "Jamaica": 74.475,
    "Jordan": 74.526,
    "Japan": 84.35634146,
    "Kazakhstan": 73.18,
    "Kenya": 66.699,
    "Cambodia": 69.823,
    "Kiribati": 68.369,
    "Kuwait": 75.489,
    "Lebanon": 78.93,
    "Liberia": 64.104,
    "Libya": 72.913,
    "Sri Lanka": 76.978,
    "Lesotho": 54.331,
    "Lithuania": 76.28292683,
    "Luxembourg": 82.63902439,
    "Latvia": 75.38780488,
    "Morocco": 76.68,
    "Monaco": null,
    "Moldova": 71.901,
    "Madagascar": 67.041,
    "Maldives": 78.921,
    "Mexico": 75.054,
    "Marshall Islands": null,
    "North Macedonia": 76.60243902,
    "Mali": 59.306,
    "Malta": 82.85853659,
    "Myanmar": 67.134,
    "Montenegro": 76.68292683,
    "Mongolia": 69.87,
    "Northern Mariana Islands": null,
    "Mozambique": 60.854,
    "Mauritania": 64.925,
    "Mauritius": 74.23585366,
    "Malawi": 64.263,
    "Malaysia": 76.156,
    "Namibia": 63.708,
    "Niger": 62.42,
    "Nigeria": 54.687,
    "Nicaragua": 74.485,
    "Netherlands": 82.11219512,
    "Norway": 82.95853659,
    "Nepal": 70.778,
    "Nauru": null,
    "New Zealand": 81.70731707,
    "Oman": 77.861,
    "Pakistan": 67.273,
    "Panama": 78.506,
    "Peru": 76.736,
    "Philippines": 71.231,
    "Palau": null,
    "Papua New Guinea": 64.501,
    "Poland": 77.90487805,
    "Puerto Rico": 79.9285122,
    "Portugal": 81.67560976,
    "Paraguay": 74.254,
    "Qatar": 80.227,
    "Romania": 75.60731707,
    "Rwanda": 69.024,
    "Saudi Arabia": 75.133,
    "Sudan": 65.311,
    "Senegal": 67.941,
    "Singapore": 83.59512195,
    "Solomon Islands": 72.996,
    "Sierra Leone": 54.696,
    "El Salvador": 73.317,
    "San Marino": null,
    "Somalia": 57.397,
    "Serbia": 75.93658537,
    "South Sudan": 57.846,
    "Sao Tome and Principe": 70.385,
    "Suriname": 71.682,
    "Slovenia": 81.52926829,
    "Sweden": 83.1097561,
    "Eswatini": 60.194,
    "Seychelles": 74.04634146,
    "Chad": 54.239,
    "Togo": 61.042,
    "Thailand": 77.15,
    "Tajikistan": 71.097,
    "Turkmenistan": 68.191,
    "Tonga": 70.907,
    "Trinidad and Tobago": 73.507,
    "Tunisia": 76.699,
    "Tuvalu": null,
    "Tanzania": 65.456,
    "Uganda": 63.368,
    "Ukraine": 71.82731707,
    "Uruguay": 77.911,
    "United States": 78.78780488,
    "Uzbekistan": 71.725,
    "Vietnam": 75.4,
    "Vanuatu": 70.474,
    "Samoa": 73.321,
    "South Africa": 64.131,
    "Zambia": 63.886,
    "Zimbabwe": 61.49
  }

const CountryIncomeCatagory = {
    "Afghanistan": "Low income",
    "Angola": "Lower middle income",
    "Albania": "Upper middle income",
    "Andorra": "High income",
    "United Arab Emirates": "High income",
    "Argentina": "Upper middle income",
    "Armenia": "Upper middle income",
    "American Samoa": "Upper middle income",
    "Antigua and Barbuda": "High income",
    "Australia": "High income",
    "Austria": "High income",
    "Azerbaijan": "Upper middle income",
    "Burundi": "Low income",
    "Belgium": "High income",
    "Benin": "Lower middle income",
    "Burkina Faso": "Low income",
    "Bangladesh": "Lower middle income",
    "Bulgaria": "Upper middle income",
    "Bahrain": "High income",
    "Bosnia and Herzegovina": "Upper middle income",
    "Belarus": "Upper middle income",
    "Belize": "Upper middle income",
    "Bermuda": "High income",
    "Bolivia": "Lower middle income",
    "Brazil": "Upper middle income",
    "Barbados": "High income",
    "Bhutan": "Lower middle income",
    "Botswana": "Upper middle income",
    "Central African Republic": "Low income",
    "Canada": "High income",
    "Switzerland": "High income",
    "Chile": "High income",
    "China": "Upper middle income",
    "Cote d'Ivoire": "Lower middle income",
    "Cameroon": "Lower middle income",
    "Colombia": "Upper middle income",
    "Comoros": "Lower middle income",
    "Costa Rica": "Upper middle income",
    "Cuba": "Upper middle income",
    "Cyprus": "High income",
    "Germany": "High income",
    "Djibouti": "Lower middle income",
    "Dominica": "Upper middle income",
    "Denmark": "High income",
    "Dominican Republic": "Upper middle income",
    "Algeria": "Lower middle income",
    "Ecuador": "Upper middle income",
    "Eritrea": "Low income",
    "Spain": "High income",
    "Estonia": "High income",
    "Ethiopia": "Low income",
    "Finland": "High income",
    "Fiji": "Upper middle income",
    "France": "High income",
    "Gabon": "Upper middle income",
    "United Kingdom": "High income",
    "Georgia": "Upper middle income",
    "Ghana": "Lower middle income",
    "Guinea": "Low income",
    "Guinea-Bissau": "Low income",
    "Equatorial Guinea": "Upper middle income",
    "Greece": "High income",
    "Grenada": "Upper middle income",
    "Greenland": "High income",
    "Guatemala": "Upper middle income",
    "Guam": "High income",
    "Guyana": "Upper middle income",
    "Honduras": "Lower middle income",
    "Croatia": "High income",
    "Haiti": "Lower middle income",
    "Hungary": "High income",
    "Indonesia": "Lower middle income",
    "India": "Lower middle income",
    "Ireland": "High income",
    "Iraq": "Upper middle income",
    "Iceland": "High income",
    "Israel": "High income",
    "Italy": "High income",
    "Jamaica": "Upper middle income",
    "Jordan": "Upper middle income",
    "Japan": "High income",
    "Kazakhstan": "Upper middle income",
    "Kenya": "Lower middle income",
    "Cambodia": "Lower middle income",
    "Kiribati": "Lower middle income",
    "Kuwait": "High income",
    "Lebanon": "Lower middle income",
    "Liberia": "Low income",
    "Libya": "Upper middle income",
    "Sri Lanka": "Lower middle income",
    "Lesotho": "Lower middle income",
    "Lithuania": "High income",
    "Luxembourg": "High income",
    "Latvia": "High income",
    "Morocco": "Lower middle income",
    "Monaco": "High income",
    "Moldova": "Upper middle income",
    "Madagascar": "Low income",
    "Maldives": "Upper middle income",
    "Mexico": "Upper middle income",
    "Marshall Islands": "Upper middle income",
    "North Macedonia": "Upper middle income",
    "Mali": "Low income",
    "Malta": "High income",
    "Myanmar": "Lower middle income",
    "Montenegro": "Upper middle income",
    "Mongolia": "Lower middle income",
    "Northern Mariana Islands": "High income",
    "Mozambique": "Low income",
    "Mauritania": "Lower middle income",
    "Mauritius": "Upper middle income",
    "Malawi": "Low income",
    "Malaysia": "Upper middle income",
    "Namibia": "Upper middle income",
    "Niger": "Low income",
    "Nigeria": "Lower middle income",
    "Nicaragua": "Lower middle income",
    "Netherlands": "High income",
    "Norway": "High income",
    "Nepal": "Lower middle income",
    "Nauru": "High income",
    "New Zealand": "High income",
    "Oman": "High income",
    "Pakistan": "Lower middle income",
    "Panama": "High income",
    "Peru": "Upper middle income",
    "Philippines": "Lower middle income",
    "Palau": "Upper middle income",
    "Papua New Guinea": "Lower middle income",
    "Poland": "High income",
    "Puerto Rico": "High income",
    "Portugal": "High income",
    "Paraguay": "Upper middle income",
    "Qatar": "High income",
    "Romania": "High income",
    "Rwanda": "Low income",
    "Saudi Arabia": "High income",
    "Sudan": "Low income",
    "Senegal": "Lower middle income",
    "Singapore": "High income",
    "Solomon Islands": "Lower middle income",
    "Sierra Leone": "Low income",
    "El Salvador": "Lower middle income",
    "San Marino": "High income",
    "Somalia": "Low income",
    "Serbia": "Upper middle income",
    "South Sudan": "Low income",
    "Sao Tome and Principe": "Lower middle income",
    "Suriname": "Upper middle income",
    "Slovenia": "High income",
    "Sweden": "High income",
    "Eswatini": "Lower middle income",
    "Seychelles": "High income",
    "Chad": "Low income",
    "Togo": "Low income",
    "Thailand": "Upper middle income",
    "Tajikistan": "Lower middle income",
    "Turkmenistan": "Upper middle income",
    "Tonga": "Upper middle income",
    "Trinidad and Tobago": "High income",
    "Tunisia": "Lower middle income",
    "Tuvalu": "Upper middle income",
    "Tanzania": "Lower middle income",
    "Uganda": "Low income",
    "Ukraine": "Lower middle income",
    "Uruguay": "High income",
    "United States": "High income",
    "Uzbekistan": "Lower middle income",
    "Vietnam": "Lower middle income",
    "Vanuatu": "Lower middle income",
    "Samoa": "Lower middle income",
    "South Africa": "Upper middle income",
    "Zambia": "Low income",
    "Zimbabwe": "Lower middle income"
  };
  
  


  const gdpData = {
    
        "GDP_2022": [
          {"Ranking": 1, "Economy": "United States", "GDP_USD_Millions": 25462700},
          {"Ranking": 2, "Economy": "China", "GDP_USD_Millions": 17963171},
          {"Ranking": 3, "Economy": "Japan", "GDP_USD_Millions": 4231141},
          {"Ranking": 4, "Economy": "Germany", "GDP_USD_Millions": 4072192},
          {"Ranking": 5, "Economy": "India", "GDP_USD_Millions": 3385090},
          {"Ranking": 6, "Economy": "United Kingdom", "GDP_USD_Millions": 3070668},
          {"Ranking": 7, "Economy": "France", "GDP_USD_Millions": 2782905},
          {"Ranking": 8, "Economy": "Russian Federation", "GDP_USD_Millions": 2240422},
          {"Ranking": 9, "Economy": "Canada", "GDP_USD_Millions": 2139840},
          {"Ranking": 10, "Economy": "Italy", "GDP_USD_Millions": 2010432},
          {"Ranking": 11, "Economy": "Brazil", "GDP_USD_Millions": 1920096},
          {"Ranking": 12, "Economy": "Australia", "GDP_USD_Millions": 1675419},
          {"Ranking": 13, "Economy": "Korea, Rep.", "GDP_USD_Millions": 1665246},
          {"Ranking": 14, "Economy": "Mexico", "GDP_USD_Millions": 1414187},
          {"Ranking": 15, "Economy": "Spain", "GDP_USD_Millions": 1397509},
          {"Ranking": 16, "Economy": "Indonesia", "GDP_USD_Millions": 1319100},
          {"Ranking": 17, "Economy": "Saudi Arabia", "GDP_USD_Millions": 1108149},
          {"Ranking": 18, "Economy": "Netherlands", "GDP_USD_Millions": 991115},
          {"Ranking": 19, "Economy": "Türkiye", "GDP_USD_Millions": 905988},
          {"Ranking": 20, "Economy": "Switzerland", "GDP_USD_Millions": 807706},
          {"Ranking": 21, "Economy": "Poland", "GDP_USD_Millions": 688177},
          {"Ranking": 22, "Economy": "Argentina", "GDP_USD_Millions": 632770},
          {"Ranking": 23, "Economy": "Sweden", "GDP_USD_Millions": 585939},
          {"Ranking": 24, "Economy": "Norway", "GDP_USD_Millions": 579267},
          {"Ranking": 25, "Economy": "Belgium", "GDP_USD_Millions": 578604},
          {"Ranking": 26, "Economy": "Cuba", "GDP_USD_Millions": 545218},
          {"Ranking": 27, "Economy": "Ireland", "GDP_USD_Millions": 529245},
          {"Ranking": 28, "Economy": "Israel", "GDP_USD_Millions": 522033},
          {"Ranking": 29, "Economy": "United Arab Emirates", "GDP_USD_Millions": 507535},
          {"Ranking": 30, "Economy": "Thailand", "GDP_USD_Millions": 495341},
          {"Ranking": 31, "Economy": "Nigeria", "GDP_USD_Millions": 477386},
          {"Ranking": 32, "Economy": "Egypt, Arab Rep.", "GDP_USD_Millions": 476748},
          {"Ranking": 33, "Economy": "Austria", "GDP_USD_Millions": 471400},
          {"Ranking": 34, "Economy": "Singapore", "GDP_USD_Millions": 466789},
          {"Ranking": 35, "Economy": "Bangladesh", "GDP_USD_Millions": 460201},
          {"Ranking": 36, "Economy": "Vietnam", "GDP_USD_Millions": 408802},
          {"Ranking": 37, "Economy": "Malaysia", "GDP_USD_Millions": 406306},
          {"Ranking": 38, "Economy": "South Africa", "GDP_USD_Millions": 405870},
          {"Ranking": 39, "Economy": "Philippines", "GDP_USD_Millions": 404284},
          {"Ranking": 40, "Economy": "Denmark", "GDP_USD_Millions": 395404},
          {"Ranking": 41, "Economy": "Iran, Islamic Rep.", "GDP_USD_Millions": 388544},
          {"Ranking": 42, "Economy": "Pakistan", "GDP_USD_Millions": 376533},
          {"Ranking": 43, "Economy": "Hong Kong SAR, China", "GDP_USD_Millions": 359839},
          {"Ranking": 44, "Economy": "Colombia", "GDP_USD_Millions": 343939},
          {"Ranking": 45, "Economy": "Romania", "GDP_USD_Millions": 301262},
          {"Ranking": 46, "Economy": "Chile", "GDP_USD_Millions": 301025},
          {"Ranking": 47, "Economy": "Czech Republic", "GDP_USD_Millions": 290924},
          {"Ranking": 48, "Economy": "Finland", "GDP_USD_Millions": 280826},
          {"Ranking": 49, "Economy": "Iraq", "GDP_USD_Millions": 264182},
          {"Ranking": 50, "Economy": "Portugal", "GDP_USD_Millions": 251945},
          {"Ranking": 51, "Economy": "New Zealand", "GDP_USD_Millions": 247234},
          {"Ranking": 52, "Economy": "Peru", "GDP_USD_Millions": 242632},
          {"Ranking": 53, "Economy": "Qatar", "GDP_USD_Millions": 237296},
          {"Ranking": 54, "Economy": "Kazakhstan", "GDP_USD_Millions": 220623},
          {"Ranking": 55, "Economy": "Greece", "GDP_USD_Millions": 219066},
          {"Ranking": 56, "Economy": "Algeria", "GDP_USD_Millions": 191913},
          {"Ranking": 57, "Economy": "Kuwait", "GDP_USD_Millions": 184558},
          {"Ranking": 58, "Economy": "Hungary", "GDP_USD_Millions": 178789},
          {"Ranking": 59, "Economy": "Ukraine", "GDP_USD_Millions": 160503},
          {"Ranking": 60, "Economy": "Morocco", "GDP_USD_Millions": 134182},
          {"Ranking": 61, "Economy": "Ethiopia", "GDP_USD_Millions": 126783},
          {"Ranking": 62, "Economy": "Slovak Republic", "GDP_USD_Millions": 115469},
          {"Ranking": 63, "Economy": "Ecuador", "GDP_USD_Millions": 115049},
          {"Ranking": 64, "Economy": "Oman", "GDP_USD_Millions": 114667},
          {"Ranking": 65, "Economy": "Dominican Republic", "GDP_USD_Millions": 113642},
          {"Ranking": 66, "Economy": "Puerto Rico", "GDP_USD_Millions": 113435},
          {"Ranking": 67, "Economy": "Kenya", "GDP_USD_Millions": 113420},
          {"Ranking": 68, "Economy": "Angola", "GDP_USD_Millions": 106714},
          {"Ranking": 69, "Economy": "Guatemala", "GDP_USD_Millions": 95003},
          {"Ranking": 70, "Economy": "Bulgaria", "GDP_USD_Millions": 89040},
          {"Ranking": 71, "Economy": "Luxembourg", "GDP_USD_Millions": 82275},
          {"Ranking": 72, "Economy": "Uzbekistan", "GDP_USD_Millions": 80392},
          {"Ranking": 73, "Economy": "Azerbaijan", "GDP_USD_Millions": 78721},
          {"Ranking": 74, "Economy": "Panama", "GDP_USD_Millions": 76523},
          {"Ranking": 75, "Economy": "Tanzania", "GDP_USD_Millions": 75709},
          {"Ranking": 76, "Economy": "Sri Lanka", "GDP_USD_Millions": 74404},
          {"Ranking": 77, "Economy": "Ghana", "GDP_USD_Millions": 72839},
          {"Ranking": 78, "Economy": "Belarus", "GDP_USD_Millions": 72793},
          {"Ranking": 79, "Economy": "Uruguay", "GDP_USD_Millions": 71177},
          {"Ranking": 80, "Economy": "Croatia", "GDP_USD_Millions": 70965},
          {"Ranking": 81, "Economy": "Lithuania", "GDP_USD_Millions": 70334},
          {"Ranking": 82, "Economy": "Côte d'Ivoire", "GDP_USD_Millions": 70019},
          {"Ranking": 83, "Economy": "Costa Rica", "GDP_USD_Millions": 68381},
          {"Ranking": 84, "Economy": "Serbia", "GDP_USD_Millions": 63502},
          {"Ranking": 85, "Economy": "Slovenia", "GDP_USD_Millions": 62118},
          {"Ranking": 86, "Economy": "Myanmar", "GDP_USD_Millions": 59364},
          {"Ranking": 87, "Economy": "Congo, Dem. Rep.", "GDP_USD_Millions": 58066},
          {"Ranking": 88, "Economy": "Sudan", "GDP_USD_Millions": 51662},
          {"Ranking": 89, "Economy": "Jordan", "GDP_USD_Millions": 47451},
          {"Ranking": 90, "Economy": "Tunisia", "GDP_USD_Millions": 46665},
          {"Ranking": 91, "Economy": "Libya", "GDP_USD_Millions": 45752},
          {"Ranking": 92, "Economy": "Turkmenistan", "GDP_USD_Millions": 45611},
          {"Ranking": 93, "Economy": "Uganda", "GDP_USD_Millions": 45559},
          {"Ranking": 94, "Economy": "Bahrain", "GDP_USD_Millions": 44391},
          {"Ranking": 95, "Economy": "Cameroon", "GDP_USD_Millions": 44342},
          {"Ranking": 96, "Economy": "Bolivia", "GDP_USD_Millions": 43069},
          {"Ranking": 97, "Economy": "Paraguay", "GDP_USD_Millions": 41722},
          {"Ranking": 98, "Economy": "Latvia", "GDP_USD_Millions": 41154},
          {"Ranking": 99, "Economy": "Nepal", "GDP_USD_Millions": 40828},
          {"Ranking": 100, "Economy": "Estonia", "GDP_USD_Millions": 38101},
          {"Ranking": 101, "Economy": "El Salvador", "GDP_USD_Millions": 32489},
          {"Ranking": 102, "Economy": "Honduras", "GDP_USD_Millions": 31718},
          {"Ranking": 103, "Economy": "Papua New Guinea", "GDP_USD_Millions": 30633},
          {"Ranking": 104, "Economy": "Cambodia", "GDP_USD_Millions": 29957},
          {"Ranking": 105, "Economy": "Zambia", "GDP_USD_Millions": 29784},
          {"Ranking": 106, "Economy": "Cyprus", "GDP_USD_Millions": 28439},
          {"Ranking": 107, "Economy": "Trinidad and Tobago", "GDP_USD_Millions": 27899},
          {"Ranking": 108, "Economy": "Iceland", "GDP_USD_Millions": 27842},
          {"Ranking": 109, "Economy": "Senegal", "GDP_USD_Millions": 27684},
          {"Ranking": 110, "Economy": "Georgia", "GDP_USD_Millions": 24605},
          {"Ranking": 111, "Economy": "Bosnia and Herzegovina", "GDP_USD_Millions": 24528},
          {"Ranking": 112, "Economy": "Lebanon", "GDP_USD_Millions": 23132},
          {"Ranking": 113, "Economy": "Macao SAR, China", "GDP_USD_Millions": 21979},
          {"Ranking": 114, "Economy": "Guinea", "GDP_USD_Millions": 21228},
          {"Ranking": 115, "Economy": "Gabon", "GDP_USD_Millions": 21072},
          {"Ranking": 116, "Economy": "Zimbabwe", "GDP_USD_Millions": 20678},
          {"Ranking": 117, "Economy": "Botswana", "GDP_USD_Millions": 20352},
          {"Ranking": 118, "Economy": "Haiti", "GDP_USD_Millions": 20254},
          {"Ranking": 119, "Economy": "Armenia", "GDP_USD_Millions": 19503},
          {"Ranking": 120, "Economy": "West Bank and Gaza", "GDP_USD_Millions": 19112},
          {"Ranking": 121, "Economy": "Burkina Faso", "GDP_USD_Millions": 18885},
          {"Ranking": 122, "Economy": "Albania", "GDP_USD_Millions": 18882},
          {"Ranking": 123, "Economy": "Mali", "GDP_USD_Millions": 18827},
          {"Ranking": 124, "Economy": "Mozambique", "GDP_USD_Millions": 17851},
          {"Ranking": 125, "Economy": "Malta", "GDP_USD_Millions": 17765},
          {"Ranking": 126, "Economy": "Benin", "GDP_USD_Millions": 17402},
          {"Ranking": 127, "Economy": "Jamaica", "GDP_USD_Millions": 17098},
          {"Ranking": 128, "Economy": "Mongolia", "GDP_USD_Millions": 16811},
          {"Ranking": 129, "Economy": "Brunei Darussalam", "GDP_USD_Millions": 16682},
          {"Ranking": 130, "Economy": "Lao PDR", "GDP_USD_Millions": 15724},
          {"Ranking": 131, "Economy": "Nicaragua", "GDP_USD_Millions": 15672},
          {"Ranking": 132, "Economy": "Guyana", "GDP_USD_Millions": 15358},
          {"Ranking": 133, "Economy": "Madagascar", "GDP_USD_Millions": 14955},
          {"Ranking": 134, "Economy": "Congo, Rep.", "GDP_USD_Millions": 14616},
          {"Ranking": 135, "Economy": "Afghanistan", "GDP_USD_Millions": 14583},
          {"Ranking": 136, "Economy": "Moldova", "GDP_USD_Millions": 14421},
          {"Ranking": 137, "Economy": "Niger", "GDP_USD_Millions": 13970},
          {"Ranking": 138, "Economy": "North Macedonia", "GDP_USD_Millions": 13563},
          {"Ranking": 139, "Economy": "Rwanda", "GDP_USD_Millions": 13313},
          {"Ranking": 140, "Economy": "Malawi", "GDP_USD_Millions": 13165},
          {"Ranking": 141, "Economy": "Mauritius", "GDP_USD_Millions": 12898},
          {"Ranking": 142, "Economy": "Bahamas, The", "GDP_USD_Millions": 12897},
          {"Ranking": 143, "Economy": "Chad", "GDP_USD_Millions": 12704},
          {"Ranking": 144, "Economy": "Namibia", "GDP_USD_Millions": 12607},
          {"Ranking": 145, "Economy": "Equatorial Guinea", "GDP_USD_Millions": 11814},
          {"Ranking": 146, "Economy": "Channel Islands", "GDP_USD_Millions": 11736},
          {"Ranking": 147, "Economy": "Syrian Arab Republic", "GDP_USD_Millions": 11159},
          {"Ranking": 148, "Economy": "Kyrgyz Republic", "GDP_USD_Millions": 10931},
          {"Ranking": 149, "Economy": "Tajikistan", "GDP_USD_Millions": 10492},
          {"Ranking": 150, "Economy": "Mauritania", "GDP_USD_Millions": 10375},
          {"Ranking": 151, "Economy": "New Caledonia", "GDP_USD_Millions": 10071},
          {"Ranking": 152, "Economy": "Kosovo", "GDP_USD_Millions": 9429},
          {"Ranking": 153, "Economy": "Monaco", "GDP_USD_Millions": 8596},
          {"Ranking": 154, "Economy": "Togo", "GDP_USD_Millions": 8126},
          {"Ranking": 155, "Economy": "Somalia", "GDP_USD_Millions": 8126},
          {"Ranking": 156, "Economy": "Bermuda", "GDP_USD_Millions": 7551},
          {"Ranking": 157, "Economy": "Liechtenstein", "GDP_USD_Millions": 7186},
          {"Ranking": 158, "Economy": "Isle of Man", "GDP_USD_Millions": 6684},
          {"Ranking": 159, "Economy": "Maldives", "GDP_USD_Millions": 6190},
          {"Ranking": 160, "Economy": "Guam", "GDP_USD_Millions": 6123},
          {"Ranking": 161, "Economy": "Montenegro", "GDP_USD_Millions": 6096},
          {"Ranking": 162, "Economy": "French Polynesia", "GDP_USD_Millions": 6080},
          {"Ranking": 163, "Economy": "Cayman Islands", "GDP_USD_Millions": 6028},
          {"Ranking": 164, "Economy": "Barbados", "GDP_USD_Millions": 5638},
          {"Ranking": 165, "Economy": "Fiji", "GDP_USD_Millions": 4943},
          {"Ranking": 166, "Economy": "Eswatini", "GDP_USD_Millions": 4854},
          {"Ranking": 167, "Economy": "Virgin Islands (U.S.)", "GDP_USD_Millions": 4204},
          {"Ranking": 168, "Economy": "Liberia", "GDP_USD_Millions": 4001},
          {"Ranking": 169, "Economy": "Sierra Leone", "GDP_USD_Millions": 3970},
          {"Ranking": 170, "Economy": "Faroe Islands", "GDP_USD_Millions": 3650},
          {"Ranking": 171, "Economy": "Suriname", "GDP_USD_Millions": 3621},
          {"Ranking": 172, "Economy": "Djibouti", "GDP_USD_Millions": 3515},
          {"Ranking": 173, "Economy": "Andorra", "GDP_USD_Millions": 3352},
          {"Ranking": 174, "Economy": "Greenland", "GDP_USD_Millions": 3236},
          {"Ranking": 175, "Economy": "Timor-Leste", "GDP_USD_Millions": 3163},
          {"Ranking": 176, "Economy": "Aruba", "GDP_USD_Millions": 3126},
          {"Ranking": 177, "Economy": "Burundi", "GDP_USD_Millions": 3073},
          {"Ranking": 178, "Economy": "Belize", "GDP_USD_Millions": 2824},
          {"Ranking": 179, "Economy": "Curaçao", "GDP_USD_Millions": 2700},
          {"Ranking": 180, "Economy": "Lesotho", "GDP_USD_Millions": 2553},
          {"Ranking": 181, "Economy": "Bhutan", "GDP_USD_Millions": 2540},
          {"Ranking": 182, "Economy": "Central African Republic", "GDP_USD_Millions": 2383},
          {"Ranking": 183, "Economy": "Cabo Verde", "GDP_USD_Millions": 2315},
          {"Ranking": 184, "Economy": "Gambia, The", "GDP_USD_Millions": 2273},
          {"Ranking": 185, "Economy": "St. Lucia", "GDP_USD_Millions": 2065},
          {"Ranking": 186, "Economy": "San Marino", "GDP_USD_Millions": 1855},
          {"Ranking": 187, "Economy": "Antigua and Barbuda", "GDP_USD_Millions": 1758},
          {"Ranking": 188, "Economy": "Guinea-Bissau", "GDP_USD_Millions": 1634},
          {"Ranking": 189, "Economy": "Solomon Islands", "GDP_USD_Millions": 1596},
          {"Ranking": 190, "Economy": "Seychelles", "GDP_USD_Millions": 1588},
          {"Ranking": 191, "Economy": "Sint Maarten (Dutch part)", "GDP_USD_Millions": 1572},
          {"Ranking": 192, "Economy": "Grenada", "GDP_USD_Millions": 1256},
          {"Ranking": 193, "Economy": "Comoros", "GDP_USD_Millions": 1243},
          {"Ranking": 194, "Economy": "Turks and Caicos Islands", "GDP_USD_Millions": 1139},
          {"Ranking": 195, "Economy": "Vanuatu", "GDP_USD_Millions": 984},
          {"Ranking": 196, "Economy": "St. Kitts and Nevis", "GDP_USD_Millions": 962},
          {"Ranking": 197, "Economy": "St. Vincent and the Grenadines", "GDP_USD_Millions": 949},
          {"Ranking": 198, "Economy": "Northern Mariana Islands", "GDP_USD_Millions": 858},
          {"Ranking": 199, "Economy": "Samoa", "GDP_USD_Millions": 832},
          {"Ranking": 200, "Economy": "American Samoa", "GDP_USD_Millions": 709},
          {"Ranking": 201, "Economy": "Dominica", "GDP_USD_Millions": 612},
          {"Ranking": 202, "Economy": "São Tomé and Principe", "GDP_USD_Millions": 547},
          {"Ranking": 203, "Economy": "Tonga", "GDP_USD_Millions": 469},
          {"Ranking": 204, "Economy": "Micronesia, Fed. Sts.", "GDP_USD_Millions": 427}
      ]
      
};

async function fetchCountryData(country) {
    const response = await fetch(`https://restcountries.com/v3.1/name/${country}?fullText=true`);
    if (!response.ok) {
        throw new Error(`Country ${country} not found`);
    }
    const data = await response.json();
    return data[0];
}

function getGDPData(countryName) {
    const countryGDP = gdpData.GDP_2022.find(entry => entry.Economy === countryName);
    return countryGDP ? countryGDP.GDP_USD_Millions : 'N/A';
}

function getAdditionalCountryData(countryName) {
    const countryCode = countryCodeData[countryName];
    const corruptionIndex = corruptionIndexData[countryName];
    const continent = countryContinentData[countryName];
    const lifeExpectancy = CountryAvgLifeExpectancy[countryName];
    const incomeCategory = CountryIncomeCatagory[countryName];
    const gdp = getGDPData(countryName);
    return { corruptionIndex, continent, lifeExpectancy, incomeCategory, gdp };
}

async function compareCountries() {
    const country1 = document.getElementById('country1').value;
    const country2 = document.getElementById('country2').value;

    try {
        const data1 = await fetchCountryData(country1);
        const data2 = await fetchCountryData(country2);

        const additionalData1 = getAdditionalCountryData(data1.name.common);
        const additionalData2 = getAdditionalCountryData(data2.name.common);

        const results = document.getElementById('results');
        
        // Check if results element exists
        if (!results) {
            console.error("The results container is missing in the DOM.");
            return;
        }

        // Create table for displaying data
        const tableHTML = `
            <table>
                <thead>
                    <tr><th>Attribute</th><th>${data1.name.common}</th><th>${data2.name.common}</th></tr>
                </thead>
                <tbody>
                    <tr><td>Area (sq km)</td><td>${data1.area}</td><td>${data2.area}</td></tr>
                    <tr><td>Population</td><td>${data1.population}</td><td>${data2.population}</td></tr>
                    <tr><td>GDP (USD Millions)</td><td>${additionalData1.gdp}</td><td>${additionalData2.gdp}</td></tr>
                    <tr><td>Corruption Index</td><td>${additionalData1.corruptionIndex || 'N/A'}</td><td>${additionalData2.corruptionIndex || 'N/A'}</td></tr>
                    <tr><td>Life Expectancy</td><td>${additionalData1.lifeExpectancy || 'N/A'}</td><td>${additionalData2.lifeExpectancy || 'N/A'}</td></tr>
                    <tr><td>Continent</td><td>${additionalData1.continent}</td><td>${additionalData2.continent}</td></tr>
                </tbody>
            </table>
        `;

        results.innerHTML = tableHTML + `<div id="chartsContainer"></div>`;

        // D3.js chart code for each data
        const chartData = [
            { attribute: 'Area (sq km)', values: [data1.area, data2.area] },
            { attribute: 'Population', values: [data1.population, data2.population] },
            { attribute: 'GDP (USD Millions)', values: [additionalData1.gdp, additionalData2.gdp] },
            { attribute: 'Corruption Index', values: [additionalData1.corruptionIndex || 0, additionalData2.corruptionIndex || 0] },
            { attribute: 'Life Expectancy', values: [additionalData1.lifeExpectancy || 0, additionalData2.lifeExpectancy || 0] }
        ];

        const chartsContainer = d3.select("#chartsContainer");

        chartData.forEach(d => {
            const chartDiv = chartsContainer.append("div").attr("class", "chart");
            createBarChart(chartDiv.node(), d.attribute, [data1.name.common, data2.name.common], d.values);
        });

    } catch (error) {
        document.getElementById('results').innerHTML = `<p>Error: ${error.message}</p>`;
    }
}


function createBarChart(element, title, labels, data) {
    const svg = d3.select(element).append("svg")
        .attr("width", 400)
        .attr("height", 400);

    const margin = { top: 30, right: 50, bottom: 50, left: 80 };
    const width = 400 - margin.left - margin.right;
    const height = 400 - margin.top - margin.bottom;

    const x = d3.scaleBand()
        .domain(labels)
        .range([0, width])
        .padding(0.2);

    const y = d3.scaleLinear()
        .domain([0, d3.max(data)])
        .nice()
        .range([height, 0]);

    const g = svg.append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

    const barColor = "steelblue";

    // Add y-axis
    g.append("g")
    .call(d3.axisLeft(y).ticks(5).tickFormat(d => {
        if (d >= 1e12) {
            return (d / 1e12).toFixed(2) + " trillion";
        } else if (d >= 1e9) {
            return (d / 1e9).toFixed(2) + " billion";
        } else if (d >= 1e6) {
            return (d / 1e6).toFixed(2) + " million";
        } else {
            return d;
        }
    }));


    g.append("g")
        .attr("transform", `translate(0,${height})`)
        .call(d3.axisBottom(x));

    g.selectAll(".bar")
        .data(data)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", (d, i) => x(labels[i]))
        .attr("y", d => y(d))
        .attr("width", x.bandwidth())
        .attr("height", d => height - y(d))
        .attr("fill", barColor)
        .on("mouseover", function(event, d) {
            d3.select(this)
                .attr("fill", d3.rgb(barColor).darker(2));
            showTooltip(event, d);
        })
        .on("mouseout", function() {
            d3.select(this)
                .attr("fill", barColor);
            hideTooltip();
        });

    svg.append("text")
        .attr("x", (width + margin.left + margin.right) / 2)
        .attr("y", margin.top / 2)
        .attr("text-anchor", "middle")
        .attr("font-size", "16px")
        .attr("font-weight", "bold")
        .text(title);

    const tooltip = d3.select("body").append("div")
        .attr("class", "tooltip")
        .style("position", "absolute")
        .style("background-color", "white")
        .style("border", "1px solid #ccc")
        .style("padding", "5px")
        .style("display", "none");

    function showTooltip(event, d) {
        tooltip
            .style("left", event.pageX + 10 + "px")
            .style("top", event.pageY - 25 + "px")
            .style("display", "inline-block")
            .html("Value: " + d3.format(",")(d));
    }

    function hideTooltip() {
        tooltip.style("display", "none");
    }
}
